site_name: Nubi2Go Docs
site_url: https://nubi2go.com/docs/
theme:
  name: material
  logo: assets/favicon.png
  favicon: assets/favicon.png
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
markdown_extensions:
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true 
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Home: index.md
  - Services:
    - Nubi Compute Service: nubi_compute_service.md
    - Flexible Block Storage: flexible_block_storage.md
    - Object Storage Service: object_storage_service.md
    - Nubi Monitoring Service: nubi_monitoring_service.md
    - Virtual Private Cloud: virtual_private_cloud.md
extra_css:
  - stylesheets/extra.css
